server.port: 8888

my:
  greeting: Hello World
  list:
    values: One, Two, Three
  
spring.cloud.config.server.git.uri: C:\Users\3732669\OneDrive - MyFedEx\Desktop\Anuja\Monthly Work\Oct20121\28 Oct\code\configrepo